#!/usr/bin/env python

# Copyright (c) 2014 University of Toronto
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# vim: tabstop=4 shiftwidth=4 softtabstop=4 expandtab

import novaclient.v1_1.client as nclient
from novaclient import exceptions

import config2 as config

#Delete VMs that match instance prefix
def delete_vms(nova):
    for s in nova.servers.list():
        if config.instance_prefix in s.name:
            print "Deleting " + s.name
            s.delete()

if __name__ == "__main__":
    #Create nova and quantum instance
    nova = nclient.Client(config.username, config.password, config.tenant_name, config.auth_url, region_name=config.region_name, no_cache=True)

    #Delete any existing VMs
    delete_vms(nova)

